export { albumAPI } from './album';
export { artistAPI } from './artist';
export { authAPI } from './auth';
export { configAPI } from './config';
export { permissionAPI } from './permission';
export { resourceAPI } from './resource';
export { showAPI } from './show';
export { trackAPI } from './track';
export { userAPI } from './user';
